services:
  tritonserver: &base
    build:
      dockerfile: .docker/Dockerfile
      target: tritonserver
    container_name: tritonserver-bert-cpu
    image: tritonserver-bert:latest
    environment:
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
    network_mode: host
    volumes:
      - "./models/topic_classification_bls:/models/topic_classification_bls"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"

  tritonclient:
    image: nvcr.io/nvidia/tritonserver:25.01-py3-sdk
    network_mode: host
    tty: true
    volumes:
      - ./client:/client
    working_dir: /client

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    network_mode: host
    ports:
      - "9090:9090"
    volumes:
      - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./metrics/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./metrics/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./metrics/grafana/dashboards:/etc/grafana/dashboards
