{
 "title": "Rigid Pipeline's Tritonserver Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Inference request success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nv_inference_request_success{model=\"rigid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nv_inference_request_duration_us{model=\"rigid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference pending count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nv_inference_pending_request_count{model=\"rigid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference queue duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "nv_inference_queue_duration_us{model=\"rigid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "nv_cpu_utilization{job=\"triton\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "nv_cpu_memory_used_bytes{job=\"triton\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "nv_cpu_memory_total_bytes{job=\"triton\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}