name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rye
      run: |
        curl -sSf https://rye-up.com/get | bash
        echo "$HOME/.rye/env" >> $GITHUB_PATH

    - name: Sync dependencies
      run: rye sync --no-lock

    - name: Run linters
      run: rye run lint

    - name: Run formatters
      run: rye run format

  build-package:
    runs-on: ubuntu-latest
    needs: lint-format
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rye
      run: |
        curl -sSf https://rye-up.com/get | bash
        echo "$HOME/.rye/shims" >> $GITHUB_PATH

    - name: Build wheel
      run: rye build

    - name: Publish package
      uses: actions/upload-artifact@v3
      with:
        name: python-package
        path: dist/*.whl

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-format
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-docs:
    runs-on: ubuntu-latest
    needs: [build-package, docker-build]
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Setup MkDocs
      run: rye add mkdocs --dev && rye sync

    - name: Build docs
      run: rye run mkdocs build --site-dir docs/_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
